#!/usr/bin/env bash
#  wget -qO- "https://github.com/alecrabbit/dev-app-makefile/archive/refs/tags/0.0.10.tar.gz" \
#  | tar -xz && shopt -s dotglob && cp -rv dev-app-makefile-0.0.10/* .\
#  && shopt -u dotglob && rm -r dev-app-makefile-0.0.10
__MAKE_DIR=".make"

if [ ! -d "${__MAKE_DIR}" ]; then
    mkdir "${__MAKE_DIR}"
    shopt -s dotglob && cp -rv ./.tools/.dam/.dist/"${__MAKE_DIR}"/* "${__MAKE_DIR}" && shopt -u dotglob
fi

# delete this file
echo "Deleting ${0}"
rm -v "${0}"
