#!/usr/bin/env bash

__MAKE_DIR=".make"

if [ ! -d "${__MAKE_DIR}" ]; then
    mkdir "${__MAKE_DIR}"
    shopt -s dotglob && cp -rv ./.tools/.dam/.dist/"${__MAKE_DIR}"/* "${__MAKE_DIR}" && shopt -u dotglob
fi

# delete this file
echo "Deleting ${0}"
rm -v "${0}"
